sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: sql123456.

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNM6tR1BLBdAKix6XMe
    access-key-secret: 1Grc3sb9i0JmLiXIP75PmhFg81XcQ6
    bucket-name: jesse-sky-take-out

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

